### ISSUE TITLE
Duplicates on Concelho and Distrito

### ISSUE THREAD

**Issue by cityxdev** [vostpt/ICNF_DATA#3]
There are duplicates on Concelho and Distrito in file SANKEY.csv.

**Comment by cityxdev** [comment]
I tried to create a branch for a pull request, but don't really know how.
I include a fix suggestion on file updater.py. Keep in mind that I don't really know my Python, so it can be a bit naive.

[updater.zip](https://github.com/vostpt/ICNF_DATA/files/9303199/updater.zip)
.

**Comment by JorgeMiguelGomes** [comment]
Hi @cityxdev **[here](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/managing-branches)** you can find the instructions on how to open a branch. I will be deleting your comment as it contains a zip file that is not a good practice.

**Comment by cityxdev** [comment]
Fixed: https://github.com/vostpt/ICNF_DATA/pull/4
